services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - competehub

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=ComPeteHub
    ports:
      - 5432:5432
    networks:
      - competehub

  debug:
    image: alpine:latest
    command: sleep infinity
    networks:
      - competehub
networks:
  competehub:
    driver: bridge