name: Go build and test

# on:
#   push:
#     branches:
#       - development
#       - main

on: [push]

jobs:
  build:

    runs-on: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.23.4
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
          cache-dependency-path: ./go.sum

      - name: display version
        run: go version

      - name: compile
        run: go build -o ./build/backend main.go

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.23.4
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
          cache-dependency-path: ./go.sum

      - name: test
        run: go test