name: Go build test

on: [push]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.23.4
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
          cache-dependency-path: ./go.sum

      - name: display version
        run: go version

      - name: compile
        run: go build -o ./build/backend main.go

  build-windows:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.23.4
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
          cache-dependency-path: ./go.sum

      - name: display version
        run: go version

      - name: compile
        run: go build -o ./build/backend main.go


  test:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.23.4
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
          cache-dependency-path: ./go.sum

      - name: test
        run: go test