name: Go build test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.23.4
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
          cache-dependency-path: ./go.sum

      - name: display version
        run: go version

      - name: compile
        run: go build -o ./build/backend main.go