name: lint go

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go 1.23.4
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
      